
spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/bankdb
    username: postgres
    password: gh5k8f12
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
jwt:
  secret: supersecretkey12345

springdoc:
  api-docs:
    path: /v3/api-docs
    resolve-schema-properties: true
  swagger-ui:
    path: /swagger-ui.html
